### ISSUE TITLE
Unstable network when partial connectivity available

### ISSUE THREAD

**Issue by glcheng** [scalecube/scalecube-cluster#187] opened 2019-04-23 09:04 UTC
Hi,

We've been experiencing continuously crashing nodes under the following condition:
- A node is able to connect to a seed node
- The same node cannot receive incoming connections

This will cause disconnect/dead messages in the whole network, and these messages will keep being generated, as the node with the partial connectivity will keep connecting. At some point there are so many messages being passed around, nodes start dying because of OOM errors.

**Comment by artem-v** [comment] 2019-05-07 20:45
Hi 

---
> This will cause disconnect/dead messages in the whole network and these messages will keep being generated, as the node with the partial connectivity will keep connecting

**On Seed:**
`Seed` can't connect back to `node`, that's why `seed ` will not send SyncAck. But it would successfully update its own membership table, though. Making possible further Ping requests, which would fail because of no connectivity from `seed` to `node`. Failed Ping (or succeeded one)  would result in certain FailureDetectorEvent (suspected/trusted), which shall be spread by Gossip algorithm. Gossip algorithm will eventually try to send accumulated msgs, and would fail, because of no connectivity from `seed` to `node`. 

**On Node:**
`Node` can connect to `seed` and will send successfully Sync request to it, so `seed`  would update his membership table. But because of no connectivity from `seed` to `node` SyncAck will not come back on `node` (but `node` doesn't care, he will start periodic Sync anyway).  Not getting SyncAck means -- `FailureDetector.pingMembers` and `Gossip.remoteMembers` both will be empty on `seed`, so algorithms would not work (they will wake up on schedule, detect that there're no endpoints to operate on, and return back to sleep). 

---
> At some point there are so many messages being passed around, nodes start dying because of OOM errors.

To narrow down the problem I suggest to deploy `seed` and `node` on two separate jvms. Though,there are few assumptions:  
1. Sending fast enough via non-connectable address using `transport.send(msg)`  will result in OOM.

**Comment by glcheng** [comment] 2019-05-08 14:28
It's the non-connectable address that causes this. If all the correct firewall rules are in place, it's fine. But if someone forgets to open up the port, it will eventually bring down the cluster. And because we auto restart any crashed node immediately, it will only cause more messages to crash the network. We can only recover, when we keep all the nodes offline, and then start them up simultaneously.

**Comment by artem-v** [comment] 2019-05-09 13:45
@glcheng 
Reproduced you problem locally. 
The problem is -- nodes with no-inbound connectivity could't be removed from the cluster  upon  their restart.  
Will work on it.

**Comment by artem-v** [comment] 2019-05-13 06:36
Fixed  this defect  at  https://github.com/scalecube/scalecube-cluster/pull/189
I tested so far manually
You can build snapshot  from  that  branch  and  check  on  your  env
Meanwhile  I will write  tests

**Comment by artem-v** [comment] 2019-05-13 16:20
@glcheng FYI finished with tests, merged to develop.

**Comment by glcheng** [comment] 2019-05-14 08:29
Thanks, I will test it out.

**Closed** 2019-06-11 19:20 UTC
